### PR TITLE
Use `files` in package.json

### PR DESCRIPTION
**Pull request by SimenB**
Reduce number of files included when `npm install`ing this package.

Before: http://hastebin.com/hixixibila.sh
After:  http://hastebin.com/evexobegam.sh

### CODE REVIEW

**Comment by mahdi-shojaee** [comment]
Why you renamed LICENSE file?

**Comment by SimenB** [comment]
That way, npm automatically picks it up, so I don't have to include it in `files` :smile:

**Comment by mehdishojaei** [comment]
Good point. Thanks.

**Comment by mahdi-shojaee** [comment]
Good point. Thanks.

**Pull request merged**
